## Dataset 1

In [143]:
import pandas as pd
df1=pd.read_csv(r"C:\Users\panka\Downloads\AI_Engineer\Projects\Data\New\TMDB_all_movies2.csv")

In [144]:
df1.head(2)

,Unnamed: 0,title,vote_average,release_date,runtime,imdb_id,overview,tagline,genres,cast,director,poster_path,keywords
0,0,Ariel,7.118,1988-10-21,73.0,tt0094675,A Finnish man goes to the city to find a job a...,NaN,"Comedy, Drama, Romance, Crime","Turo Pajala, Susanna Haavisto, Matti Pellonpää...",Aki Kaurismäki,/ojDg0PGvs6R9xYFodRct2kdI6wC.jpg,"prison|underdog|helsinki, finland|factory work..."
1,1,Shadows in Paradise,7.300,1986-10-17,74.0,tt0092149,"Nikander, a rubbish collector and would-be ent...",NaN,"Comedy, Drama, Romance","Matti Pellonpää, Kati Outinen, Sakari Kuosmane...",Aki Kaurismäki,/nj01hspawPof0mJmlgfjuLyJuRN.jpg,"helsinki, finland|salesclerk|garbage"

In [145]:
df1.isnull().sum()

Unnamed: 0           0
title                0
vote_average         0
release_date      4511
runtime              0
imdb_id          53578
overview             0
tagline         264404
genres               0
cast             27353
director         15274
poster_path      25903
keywords        201201
dtype: int64

In [146]:
df1=df1[df1["runtime"]>60]

In [147]:
df1.shape

(361115, 13)

In [148]:
df1.head(3)

,Unnamed: 0,title,vote_average,release_date,runtime,imdb_id,overview,tagline,genres,cast,director,poster_path,keywords
0,0,Ariel,7.118,1988-10-21,73.0,tt0094675,A Finnish man goes to the city to find a job a...,NaN,"Comedy, Drama, Romance, Crime","Turo Pajala, Susanna Haavisto, Matti Pellonpää...",Aki Kaurismäki,/ojDg0PGvs6R9xYFodRct2kdI6wC.jpg,"prison|underdog|helsinki, finland|factory work..."
1,1,Shadows in Paradise,7.300,1986-10-17,74.0,tt0092149,"Nikander, a rubbish collector and would-be ent...",NaN,"Comedy, Drama, Romance","Matti Pellonpää, Kati Outinen, Sakari Kuosmane...",Aki Kaurismäki,/nj01hspawPof0mJmlgfjuLyJuRN.jpg,"helsinki, finland|salesclerk|garbage"
2,2,Four Rooms,5.905,1995-12-09,98.0,tt0113101,It's Ted the Bellhop's first night on the job....,Twelve outrageous guests. Four scandalous requ...,Comedy,"Sammi Davis, Salma Hayek Pinault, Lawrence Ben...","Quentin Tarantino, Robert Rodriguez, Alexandre...",/75aHn1NOYXh4M7L5shoeQ6NGykP.jpg,hotel|new year's eve|witch|bet|sperm|hotel roo...

In [149]:
df1.isnull().sum()

Unnamed: 0           0
title                0
vote_average         0
release_date      4511
runtime              0
imdb_id          53578
overview             0
tagline         264404
genres               0
cast             27353
director         15274
poster_path      25903
keywords        201201
dtype: int64

In [150]:
df1 = df1[~(df1["cast"].isna() & df1["director"].isna())]

In [151]:
df1.head(3)

,Unnamed: 0,title,vote_average,release_date,runtime,imdb_id,overview,tagline,genres,cast,director,poster_path,keywords
0,0,Ariel,7.118,1988-10-21,73.0,tt0094675,A Finnish man goes to the city to find a job a...,NaN,"Comedy, Drama, Romance, Crime","Turo Pajala, Susanna Haavisto, Matti Pellonpää...",Aki Kaurismäki,/ojDg0PGvs6R9xYFodRct2kdI6wC.jpg,"prison|underdog|helsinki, finland|factory work..."
1,1,Shadows in Paradise,7.300,1986-10-17,74.0,tt0092149,"Nikander, a rubbish collector and would-be ent...",NaN,"Comedy, Drama, Romance","Matti Pellonpää, Kati Outinen, Sakari Kuosmane...",Aki Kaurismäki,/nj01hspawPof0mJmlgfjuLyJuRN.jpg,"helsinki, finland|salesclerk|garbage"
2,2,Four Rooms,5.905,1995-12-09,98.0,tt0113101,It's Ted the Bellhop's first night on the job....,Twelve outrageous guests. Four scandalous requ...,Comedy,"Sammi Davis, Salma Hayek Pinault, Lawrence Ben...","Quentin Tarantino, Robert Rodriguez, Alexandre...",/75aHn1NOYXh4M7L5shoeQ6NGykP.jpg,hotel|new year's eve|witch|bet|sperm|hotel roo...

In [152]:
df1.shape

(361115, 13)

In [153]:
df1.isnull().sum()

Unnamed: 0           0
title                0
vote_average         0
release_date      4511
runtime              0
imdb_id          53578
overview             0
tagline         264404
genres               0
cast             27353
director         15274
poster_path      25903
keywords        201201
dtype: int64

In [154]:
df1["keywords"] = df1["keywords"].fillna("")

In [155]:
df1 = df1.dropna(subset=["title", "overview", "genres"])

In [156]:
df1["cast"] = df1["cast"].fillna("")
df1["director"] = df1["director"].fillna("")

In [157]:
df1.isnull().sum()

Unnamed: 0           0
title                0
vote_average         0
release_date      4511
runtime              0
imdb_id          53578
overview             0
tagline         264404
genres               0
cast                 0
director             0
poster_path      25903
keywords             0
dtype: int64

In [158]:
df1.shape

(361115, 13)

In [159]:
df1.head(2)

,Unnamed: 0,title,vote_average,release_date,runtime,imdb_id,overview,tagline,genres,cast,director,poster_path,keywords
0,0,Ariel,7.118,1988-10-21,73.0,tt0094675,A Finnish man goes to the city to find a job a...,NaN,"Comedy, Drama, Romance, Crime","Turo Pajala, Susanna Haavisto, Matti Pellonpää...",Aki Kaurismäki,/ojDg0PGvs6R9xYFodRct2kdI6wC.jpg,"prison|underdog|helsinki, finland|factory work..."
1,1,Shadows in Paradise,7.300,1986-10-17,74.0,tt0092149,"Nikander, a rubbish collector and would-be ent...",NaN,"Comedy, Drama, Romance","Matti Pellonpää, Kati Outinen, Sakari Kuosmane...",Aki Kaurismäki,/nj01hspawPof0mJmlgfjuLyJuRN.jpg,"helsinki, finland|salesclerk|garbage"

In [165]:
df1.drop(columns=["Unnamed: 0"],inplace=True)

In [166]:
df1.head(2)

,title,vote_average,release_date,runtime,imdb_id,overview,tagline,genres,cast,director,poster_path,keywords
0,Ariel,7.118,1988-10-21,73.0,tt0094675,A Finnish man goes to the city to find a job a...,NaN,"Comedy, Drama, Romance, Crime","Turo Pajala, Susanna Haavisto, Matti Pellonpää...",Aki Kaurismäki,/ojDg0PGvs6R9xYFodRct2kdI6wC.jpg,"prison|underdog|helsinki, finland|factory work..."
1,Shadows in Paradise,7.300,1986-10-17,74.0,tt0092149,"Nikander, a rubbish collector and would-be ent...",NaN,"Comedy, Drama, Romance","Matti Pellonpää, Kati Outinen, Sakari Kuosmane...",Aki Kaurismäki,/nj01hspawPof0mJmlgfjuLyJuRN.jpg,"helsinki, finland|salesclerk|garbage"

In [167]:
df1.to_csv(r"C:\Users\panka\Downloads\AI_Engineer\Projects\Data\New\TMDB_all_movies2.csv")

## Dataset 2

In [168]:
df2=pd.read_csv(r"C:\Users\panka\Downloads\AI_Engineer\Projects\Data\New\TMDB_all_movies1.csv")

In [169]:
df2.shape

(1474875, 13)

In [170]:
df2.head(2)

,id,title,vote_average,release_date,runtime,backdrop_path,homepage,imdb_id,overview,poster_path,tagline,genres,keywords
0,27205,Inception,8.364,2010-07-15,148,/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg,https://www.warnerbros.com/movies/inception,tt1375666,"Cobb, a skilled thief who commits corporate es...",/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg,Your mind is the scene of the crime.,"Action, Science Fiction, Adventure","rescue, mission, dream, airplane, paris, franc..."
1,157336,Interstellar,8.417,2014-11-05,169,/pbrkL804c8yAv3zBZR4QPEafpAR.jpg,http://www.interstellarmovie.net/,tt0816692,The adventures of a group of explorers who mak...,/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg,Mankind was born on Earth. It was never meant ...,"Adventure, Drama, Science Fiction","rescue, future, spacecraft, race against time,..."

In [171]:
df2=df2[df2["runtime"]>60]

In [172]:
df2.shape

(503437, 13)

In [173]:
df2 = df2.dropna(subset=["title", "overview", "genres"])

In [174]:
df2.shape

(316111, 13)

In [175]:
df2.isnull().sum()

id                    0
title                 0
vote_average          0
release_date       8663
runtime               0
backdrop_path    153957
homepage         265204
imdb_id           59969
overview              0
poster_path       35106
tagline          228972
genres                0
keywords         175268
dtype: int64

In [176]:
df1["keywords"] = df1["keywords"].fillna("")
df1["tagline"] = df1["tagline"].fillna("")

In [177]:
df2.head(2)

,id,title,vote_average,release_date,runtime,backdrop_path,homepage,imdb_id,overview,poster_path,tagline,genres,keywords
0,27205,Inception,8.364,2010-07-15,148,/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg,https://www.warnerbros.com/movies/inception,tt1375666,"Cobb, a skilled thief who commits corporate es...",/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg,Your mind is the scene of the crime.,"Action, Science Fiction, Adventure","rescue, mission, dream, airplane, paris, franc..."
1,157336,Interstellar,8.417,2014-11-05,169,/pbrkL804c8yAv3zBZR4QPEafpAR.jpg,http://www.interstellarmovie.net/,tt0816692,The adventures of a group of explorers who mak...,/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg,Mankind was born on Earth. It was never meant ...,"Adventure, Drama, Science Fiction","rescue, future, spacecraft, race against time,..."

In [178]:
import pandas as pd
import re

def combine_features(df, feature_list, new_col_name='combined_features', sep=' '):
    """
    Combines multiple string-based columns of a dataframe into a single new column.
    Any character that is NOT an alphabet letter (a-z, A-Z) is treated as a separator
    (this includes commas, spaces, periods, quotes, digits, hyphens, colons, etc.).

    Parameters:
        df (pd.DataFrame): The input dataframe.
        feature_list (list of str): List of column names to combine.
        new_col_name (str): Name of the new combined feature column.
        sep (str): Separator to join the final combined words with (default: single space).

    Returns:
        pd.DataFrame: The dataframe with the new combined feature column added.
    """
    df = df.copy()

    # Validate that all requested features exist in the dataframe
    missing = [f for f in feature_list if f not in df.columns]
    if missing:
        raise ValueError(f"These columns are not in the dataframe: {missing}")

    def process_row(row):
        words = []
        for feature in feature_list:
            value = row[feature]

            # Handle NaN / None gracefully
            if pd.isna(value):
                continue

            value = str(value)

            # Split on ANY non-alphabet character (letters only survive as tokens)
            tokens = re.split(r'[^a-zA-Z]+', value.strip())
            tokens = [t.strip() for t in tokens if t.strip() != '']

            words.extend(tokens)

        return sep.join(words)

    df[new_col_name] = df.apply(process_row, axis=1)
    return df

In [179]:
df2 = combine_features(df2, ['keywords', 'tagline', 'overview'], new_col_name='tags')
df2[['tags']].head(2)

                                                tags
0  rescue mission dream airplane paris france vir...
1  rescue future spacecraft race against time art...

In [180]:
df2["tags"][0]

'rescue mission dream airplane paris france virtual reality kidnapping philosophy spy allegory manipulation car crash heist memory architecture los angeles california dream world subconscious Your mind is the scene of the crime Cobb a skilled thief who commits corporate espionage by infiltrating the subconscious of his targets is offered a chance to regain his old life as payment for a task considered to be impossible inception the implantation of another person s idea into a target s subconscious'

In [181]:
df2.head(2)

,id,title,vote_average,release_date,runtime,backdrop_path,homepage,imdb_id,overview,poster_path,tagline,genres,keywords,tags
0,27205,Inception,8.364,2010-07-15,148,/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg,https://www.warnerbros.com/movies/inception,tt1375666,"Cobb, a skilled thief who commits corporate es...",/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg,Your mind is the scene of the crime.,"Action, Science Fiction, Adventure","rescue, mission, dream, airplane, paris, franc...",rescue mission dream airplane paris france vir...
1,157336,Interstellar,8.417,2014-11-05,169,/pbrkL804c8yAv3zBZR4QPEafpAR.jpg,http://www.interstellarmovie.net/,tt0816692,The adventures of a group of explorers who mak...,/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg,Mankind was born on Earth. It was never meant ...,"Adventure, Drama, Science Fiction","rescue, future, spacecraft, race against time,...",rescue future spacecraft race against time art...

In [182]:
df2.drop(columns=["tagline","keywords","overview"],inplace=True)

In [183]:
df2.head(2)

,id,title,vote_average,release_date,runtime,backdrop_path,homepage,imdb_id,poster_path,genres,tags
0,27205,Inception,8.364,2010-07-15,148,/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg,https://www.warnerbros.com/movies/inception,tt1375666,/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg,"Action, Science Fiction, Adventure",rescue mission dream airplane paris france vir...
1,157336,Interstellar,8.417,2014-11-05,169,/pbrkL804c8yAv3zBZR4QPEafpAR.jpg,http://www.interstellarmovie.net/,tt0816692,/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg,"Adventure, Drama, Science Fiction",rescue future spacecraft race against time art...

In [184]:
df2 = combine_features(df2, ['genres'], new_col_name='genre')
df2[['genre']].head(2)

                              genre
0  Action Science Fiction Adventure
1   Adventure Drama Science Fiction

In [185]:
df2.drop(columns=['genres'],inplace=True)

In [186]:
df2.head(2)

,id,title,vote_average,release_date,runtime,backdrop_path,homepage,imdb_id,poster_path,tags,genre
0,27205,Inception,8.364,2010-07-15,148,/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg,https://www.warnerbros.com/movies/inception,tt1375666,/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg,rescue mission dream airplane paris france vir...,Action Science Fiction Adventure
1,157336,Interstellar,8.417,2014-11-05,169,/pbrkL804c8yAv3zBZR4QPEafpAR.jpg,http://www.interstellarmovie.net/,tt0816692,/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg,rescue future spacecraft race against time art...,Adventure Drama Science Fiction

In [187]:
df1.head(2)

,title,vote_average,release_date,runtime,imdb_id,overview,tagline,genres,cast,director,poster_path,keywords
0,Ariel,7.118,1988-10-21,73.0,tt0094675,A Finnish man goes to the city to find a job a...,,"Comedy, Drama, Romance, Crime","Turo Pajala, Susanna Haavisto, Matti Pellonpää...",Aki Kaurismäki,/ojDg0PGvs6R9xYFodRct2kdI6wC.jpg,"prison|underdog|helsinki, finland|factory work..."
1,Shadows in Paradise,7.300,1986-10-17,74.0,tt0092149,"Nikander, a rubbish collector and would-be ent...",,"Comedy, Drama, Romance","Matti Pellonpää, Kati Outinen, Sakari Kuosmane...",Aki Kaurismäki,/nj01hspawPof0mJmlgfjuLyJuRN.jpg,"helsinki, finland|salesclerk|garbage"

In [188]:
df1 = combine_features(df1, ['keywords', 'tagline', 'overview'], new_col_name='tags')

In [189]:
df1['tags'][0]

'prison underdog helsinki finland factory worker prisoner falling in love A Finnish man goes to the city to find a job after the mine where he worked is closed and his father commits suicide'

In [190]:
df1 = combine_features(df1, ['genres'], new_col_name='genre')
df1['genre'][0]

'Comedy Drama Romance Crime'

In [191]:
df1.head(2)

,title,vote_average,release_date,runtime,imdb_id,overview,tagline,genres,cast,director,poster_path,keywords,tags,genre
0,Ariel,7.118,1988-10-21,73.0,tt0094675,A Finnish man goes to the city to find a job a...,,"Comedy, Drama, Romance, Crime","Turo Pajala, Susanna Haavisto, Matti Pellonpää...",Aki Kaurismäki,/ojDg0PGvs6R9xYFodRct2kdI6wC.jpg,"prison|underdog|helsinki, finland|factory work...",prison underdog helsinki finland factory worke...,Comedy Drama Romance Crime
1,Shadows in Paradise,7.300,1986-10-17,74.0,tt0092149,"Nikander, a rubbish collector and would-be ent...",,"Comedy, Drama, Romance","Matti Pellonpää, Kati Outinen, Sakari Kuosmane...",Aki Kaurismäki,/nj01hspawPof0mJmlgfjuLyJuRN.jpg,"helsinki, finland|salesclerk|garbage",helsinki finland salesclerk garbage Nikander a...,Comedy Drama Romance

In [192]:
df1.drop(columns=['overview','tagline','keywords'],inplace=True)

In [193]:
df1 = combine_features(df1, ['cast','director'], new_col_name='members')

In [194]:
df1['members'][0]

'Turo Pajala Susanna Haavisto Matti Pellonp Eetu Hilkamo Erkki Pajala Matti Jaaranen Hannu Viholainen Jorma Markkula Tarja Kein nen Eino Kuusela Kauko Laalo Jyrki Olsonen Esko Nikkari Marja Packal n Mikko Remes Tomi Salmela Reijo Marin Heikki Salomaa Veikko Uusim ki Esko Salminen Hannu Kivisalo Pekka Wilen Heikki Anttila Pentti Auer Timo Harakka Kari Helasepp Juuso Hirvikangas Hanna Jokinen Sakari Kuosmanen Sami Lanki Jouko Lumme Mikko Lyytik inen Timo Markko Merja Pulkkinen Markku Rantala Sirkka Rautiainen Jaakko Talaskivi Timo Toikka Olli Varja Aki Kaurism ki'

In [195]:
df1.isnull().sum()

title               0
vote_average        0
release_date     4511
runtime             0
imdb_id         53578
genres              0
cast                0
director            0
poster_path     25903
tags                0
genre               0
members             0
dtype: int64

In [196]:
df1.drop(columns=['genres','cast','director'],inplace=True)

In [197]:
df1.head(2)

,title,vote_average,release_date,runtime,imdb_id,poster_path,tags,genre,members
0,Ariel,7.118,1988-10-21,73.0,tt0094675,/ojDg0PGvs6R9xYFodRct2kdI6wC.jpg,prison underdog helsinki finland factory worke...,Comedy Drama Romance Crime,Turo Pajala Susanna Haavisto Matti Pellonp Eet...
1,Shadows in Paradise,7.300,1986-10-17,74.0,tt0092149,/nj01hspawPof0mJmlgfjuLyJuRN.jpg,helsinki finland salesclerk garbage Nikander a...,Comedy Drama Romance,Matti Pellonp Kati Outinen Sakari Kuosmanen Es...

In [198]:
df2.head(2)

,id,title,vote_average,release_date,runtime,backdrop_path,homepage,imdb_id,poster_path,tags,genre
0,27205,Inception,8.364,2010-07-15,148,/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg,https://www.warnerbros.com/movies/inception,tt1375666,/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg,rescue mission dream airplane paris france vir...,Action Science Fiction Adventure
1,157336,Interstellar,8.417,2014-11-05,169,/pbrkL804c8yAv3zBZR4QPEafpAR.jpg,http://www.interstellarmovie.net/,tt0816692,/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg,rescue future spacecraft race against time art...,Adventure Drama Science Fiction

In [199]:
import pandas as pd
import numpy as np

def smart_merge(df1, df2, key='title', priority='df1'):
    """
    Merges two dataframes on `key`, combining duplicate rows by filling
    nulls from one another instead of discarding data. When both sides
    have a value, the `priority` dataset's value wins.

    Parameters:
        df1, df2 (pd.DataFrame): Dataframes to merge.
        key (str): Column used to identify duplicate records (e.g. 'title').
        priority (str): 'df1' or 'df2' — which dataset's non-null value 
                         wins when both have a value for the same column.

    Returns:
        pd.DataFrame: One row per unique key, with maximum info retained.
    """
    df1 = df1.copy()
    df2 = df2.copy()
    df1['__source__'] = 'df1'
    df2['__source__'] = 'df2'

    combined = pd.concat([df1, df2], axis=0, ignore_index=True, sort=False)

    # Order rows so the priority dataset comes first within each group
    order = ['df1', 'df2'] if priority == 'df1' else ['df2', 'df1']
    combined['__source__'] = pd.Categorical(combined['__source__'], categories=order, ordered=True)
    combined = combined.sort_values(by=[key, '__source__'])

    other_cols = [c for c in combined.columns if c not in (key, '__source__')]

    # For each column, take the first non-null value within the group
    # (priority row's value wins if present, else falls back to the other row's)
    agg_dict = {c: (lambda s: s.dropna().iloc[0] if s.notna().any() else np.nan) for c in other_cols}
    result = combined.groupby(key, sort=False, as_index=False).agg(agg_dict)

    return result

In [210]:
df12 = smart_merge(df1, df2,key='title',priority='df1')

In [211]:
print(df1.shape, df2.shape, df12.shape)
print(df12.columns.tolist())
print(df12.isna().sum())

(361115, 9) (316111, 11) (351385, 12)
['title', 'vote_average', 'release_date', 'runtime', 'imdb_id', 'poster_path', 'tags', 'genre', 'members', 'id', 'backdrop_path', 'homepage']
title                 0
vote_average          0
release_date       5889
runtime               0
imdb_id           63731
poster_path       24647
tags                  0
genre                 0
members           34089
id                71589
backdrop_path    204755
homepage         302187
dtype: int64

In [212]:
df12.drop(columns=['id','backdrop_path','homepage'],inplace=True)

In [213]:
df12.head(2)

,title,vote_average,release_date,runtime,imdb_id,poster_path,tags,genre,members
0,! [ai-ou],5.3,1991-01-26,108.0,NaN,/nb8ValoEsJdooZDOXfOt9uH8jIr.jpg,ai ou Three outsiders meet by chance and try t...,Action Drama Crime Comedy,Shigeru Saiki Kazukiyo Nishikiori Ryuusaku Shi...
1,!Aitsa,6.0,2023-03-16,89.0,tt27009737,/wrVlKVaLKdYbFgEsPtSCaGjMkS9.jpg,The ancient knowledge of indigenous peoples ch...,Documentary,Dane Dodds

In [214]:
df12.to_csv(r'C:\Users\panka\Downloads\AI_Engineer\Projects\Data\New\Dataset_d12.csv')

## Dataset 3

In [215]:
df3=pd.read_csv(r"C:\Users\panka\Downloads\AI_Engineer\Projects\Data\New\TrendingMovies.csv")

In [216]:
df3.head(2)

,id,title,overview,vote_average,release_date
0,969681,Spider-Man: Brand New Day,Fighting crime full-time as Spider-Man in a wo...,7.864,2026-07-29
1,1368337,The Odyssey,"Odysseus, the legendary King of Ithaca, embark...",8.000,2026-07-15

In [217]:
df3.shape

(9996, 5)

In [218]:
df3 = combine_features(df3, ['overview'], new_col_name='tags')

In [219]:
df3.drop(columns=['id'],inplace=True)

In [291]:
df3.drop(columns=['overview'],inplace=True)

In [292]:
df12.columns

Index(['title', 'vote_average', 'release_date', 'runtime', 'imdb_id',
       'poster_path', 'tags', 'genre', 'members'],
      dtype='object')

In [293]:
df123 =smart_merge(df12,df3,key='title',priority='df12')

In [294]:
df123.head(2)

,title,vote_average,release_date,runtime,imdb_id,poster_path,tags,genre,members
0,! [ai-ou],5.3,1991-01-26,108.0,NaN,/nb8ValoEsJdooZDOXfOt9uH8jIr.jpg,ai ou Three outsiders meet by chance and try t...,Action Drama Crime Comedy,Shigeru Saiki Kazukiyo Nishikiori Ryuusaku Shi...
1,!Aitsa,6.0,2023-03-16,89.0,tt27009737,/wrVlKVaLKdYbFgEsPtSCaGjMkS9.jpg,The ancient knowledge of indigenous peoples ch...,Documentary,Dane Dodds

In [295]:
print(df12.shape,df123.shape)

(351385, 9) (352956, 9)

In [296]:
df123.to_csv(r'C:\Users\panka\Downloads\AI_Engineer\Projects\Data\New\Dataset_d123.csv')

## Dataset 4&5

In [227]:
df4=pd.read_csv(r"C:\Users\panka\Downloads\AI_Engineer\Projects\Data\New\indian_movies_cleaned-selected-columns.csv")

In [228]:
df4.head()

,title,overview,release_date,genres,vote_count
0,RRR,A fictional history of two legendary revolutio...,2022-03-24,Action,1020
1,Looop Lapeta,"When her boyfriend loses a mobster's cash, Sav...",2022-02-04,Action,56
2,3 Idiots,Rascal. Joker. Dreamer. Genius... You've never...,2009-12-23,Drama,2119
3,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second...",1995-10-20,Comedy,4186
4,Bāhubali: The Beginning,The young Shivudu is left as a foundling in a ...,2015-07-10,Action,681

In [229]:
df4.isnull().sum()

title           0
overview        0
release_date    0
genres          0
vote_count      0
dtype: int64

In [230]:
df5=pd.read_csv(r"C:\Users\panka\Downloads\AI_Engineer\Projects\Data\New\indian_cinema_dataset-selected-columns.csv")

In [231]:
df5.head(2)

,title,release_date,runtime_minutes,directors,cast,genres,imdb_id
0,Ishti,2016-01-01,NaN,Dr. G. Prabha,NaN,drama film,tt14214652
1,Kangan,1971-01-01,NaN,K. B. Tilak,"Sanjeev Kumar, Mala Sinha",drama film,tt0031527

In [236]:
df5.isnull().sum()

title                  0
release_date        4304
runtime_minutes    26711
directors           9231
cast                8249
genres             17192
imdb_id             2592
dtype: int64

In [232]:
df45=smart_merge(df4,df5,key='title',priority='df4')

In [241]:
df45.head(3)

,title,overview,release_date,genres,vote_count,runtime_minutes,directors,cast,imdb_id
0,"""R"" The King",NaN,NaN,NaN,NaN,NaN,Prem,Vinay Rajkumar,NaN
1,"#73, Shantinivasa",NaN,2007-06-15,NaN,NaN,NaN,Sudeepa,NaN,NaN
2,#Home,NaN,2021-08-19,NaN,NaN,161.0,Rojin Thomas,"Manju Pillai, Aju Varghese, Anoop Menon, Indra...",tt10534500

In [243]:
df45.head(3)

,title,overview,release_date,genres,vote_count,runtime_minutes,directors,cast,imdb_id
0,"""R"" The King",NaN,NaN,NaN,NaN,NaN,Prem,Vinay Rajkumar,NaN
1,"#73, Shantinivasa",NaN,2007-06-15,NaN,NaN,NaN,Sudeepa,NaN,NaN
2,#Home,NaN,2021-08-19,NaN,NaN,161.0,Rojin Thomas,"Manju Pillai, Aju Varghese, Anoop Menon, Indra...",tt10534500

In [ ]:
df45 = combine_features(df45, ['cast','directors'], new_col_name='members')

In [248]:
df45.drop(columns=['cast','directors'],inplace=True)

In [250]:
df45.head(3)

,title,overview,release_date,genres,vote_count,runtime_minutes,imdb_id,members
0,"""R"" The King",NaN,NaN,NaN,NaN,NaN,NaN,Vinay Rajkumar Prem
1,"#73, Shantinivasa",NaN,2007-06-15,NaN,NaN,NaN,NaN,Sudeepa
2,#Home,NaN,2021-08-19,NaN,NaN,161.0,tt10534500,Manju Pillai Aju Varghese Anoop Menon Indrans ...

In [275]:
df45 = combine_features(df45, ['overview'], new_col_name='tags')

In [277]:
df45.drop(columns=['overview'],inplace=True)

In [ ]:
df45.rename(columns={'runtime_minutes':'runtime'},inplace=True)

In [257]:
df45.rename(columns={'genres':'genre'},inplace=True)

In [278]:
df45.isnull().sum()

title               0
release_date     3780
genre           15228
runtime         24409
imdb_id          2467
members             0
tags                0
dtype: int64

In [ ]:
df45.drop(columns=['vote_count',],inplace=True)

In [262]:
df45.shape

(27878, 7)

In [279]:
df45.isnull().sum()

title               0
release_date     3780
genre           15228
runtime         24409
imdb_id          2467
members             0
tags                0
dtype: int64

In [281]:
common_titles = set(df4['title']) & set(df5['title'])
print("df4 rows:", len(df4))
print("df5 rows:", len(df5))
print("Exact matching titles:", len(common_titles))
print("Expected merged size if no dupes:", len(df4) + len(df5) - len(common_titles))
print("Actual df45 size:", df45.shape[0])

df4 rows: 1500
df5 rows: 30250
Exact matching titles: 1313
Expected merged size if no dupes: 30437
Actual df45 size: 27878

In [282]:
df45.shape

(27878, 7)

In [297]:
df123.head(2)

,title,vote_average,release_date,runtime,imdb_id,poster_path,tags,genre,members
0,! [ai-ou],5.3,1991-01-26,108.0,NaN,/nb8ValoEsJdooZDOXfOt9uH8jIr.jpg,ai ou Three outsiders meet by chance and try t...,Action Drama Crime Comedy,Shigeru Saiki Kazukiyo Nishikiori Ryuusaku Shi...
1,!Aitsa,6.0,2023-03-16,89.0,tt27009737,/wrVlKVaLKdYbFgEsPtSCaGjMkS9.jpg,The ancient knowledge of indigenous peoples ch...,Documentary,Dane Dodds

In [298]:
df12345=smart_merge(df123,df45,key='title',priority='df123')

In [299]:
df12345.head(2)

,title,vote_average,release_date,runtime,imdb_id,poster_path,tags,genre,members
0,! [ai-ou],5.3,1991-01-26,108.0,NaN,/nb8ValoEsJdooZDOXfOt9uH8jIr.jpg,ai ou Three outsiders meet by chance and try t...,Action Drama Crime Comedy,Shigeru Saiki Kazukiyo Nishikiori Ryuusaku Shi...
1,!Aitsa,6.0,2023-03-16,89.0,tt27009737,/wrVlKVaLKdYbFgEsPtSCaGjMkS9.jpg,The ancient knowledge of indigenous peoples ch...,Documentary,Dane Dodds

In [300]:
df12345.shape

(367178, 9)

In [302]:
df12345.isnull().sum()

title               0
vote_average    14222
release_date     8234
runtime         14951
imdb_id         66825
poster_path     40440
tags                0
genre           11007
members         35432
dtype: int64

In [303]:
df12345.to_csv(r"C:\Users\panka\Downloads\AI_Engineer\Projects\Data\New\Dataset_d12345.csv")

## Dataset 6

In [318]:
df6=pd.read_csv(r"C:\Users\panka\Downloads\AI_Engineer\Projects\Data\New\imdb_top_1000-selected-columns.csv")

In [319]:
df6.head(2)

,Poster_Link,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton

In [320]:
df12345.head(2)

,title,vote_average,release_date,runtime,imdb_id,poster_path,tags,genre,members
0,! [ai-ou],5.3,1991-01-26,108.0,NaN,/nb8ValoEsJdooZDOXfOt9uH8jIr.jpg,ai ou Three outsiders meet by chance and try t...,Action Drama Crime Comedy,Shigeru Saiki Kazukiyo Nishikiori Ryuusaku Shi...
1,!Aitsa,6.0,2023-03-16,89.0,tt27009737,/wrVlKVaLKdYbFgEsPtSCaGjMkS9.jpg,The ancient knowledge of indigenous peoples ch...,Documentary,Dane Dodds

In [321]:
df6.shape

(1000, 13)

In [322]:
df6.rename(columns={'Series_Title':'title','IMDB_Rating':'vote_average','Released_Year':'release_date','Runtime':'runtime','Genre':'genres','Poster_Link':'poster_path','Overview':'overview',},inplace=True)

In [323]:
df6.head(2)

,poster_path,title,release_date,runtime,genres,vote_average,overview,Meta_score,Director,Star1,Star2,Star3,Star4
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton

In [324]:
df6 = combine_features(df6, ['overview'], new_col_name='tags')

In [325]:
df6.drop(columns=['overview'],inplace=True)

In [326]:
df6.head(2)

,poster_path,title,release_date,runtime,genres,vote_average,Meta_score,Director,Star1,Star2,Star3,Star4,tags
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,142 min,Drama,9.3,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,Two imprisoned men bond over a number of years...
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,175 min,"Crime, Drama",9.2,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,An organized crime dynasty s aging patriarch t...

In [327]:
df6 = combine_features(df6, ['genres'], new_col_name='genre')

In [328]:
df6.drop(columns=['genres'],inplace=True)

In [329]:
df6.head(2)

,poster_path,title,release_date,runtime,vote_average,Meta_score,Director,Star1,Star2,Star3,Star4,tags,genre
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,142 min,9.3,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,Two imprisoned men bond over a number of years...,Drama
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,175 min,9.2,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,An organized crime dynasty s aging patriarch t...,Crime Drama

In [ ]:
df6 = combine_features(df6, ['Director','Star1','Star2','Star3','Star4'], new_col_name='members')

In [ ]:
df6.drop(columns=['Director','Star1','Star2','Star3','Star4'],inplace=True)
df6.drop(columns=['Meta_score'],inplace=True)

In [336]:
df6.head(2)

,poster_path,title,release_date,runtime,vote_average,tags,genre,members
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,142 min,9.3,Two imprisoned men bond over a number of years...,Drama,Frank Darabont Tim Robbins Morgan Freeman Bob ...
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,175 min,9.2,An organized crime dynasty s aging patriarch t...,Crime Drama,Francis Ford Coppola Marlon Brando Al Pacino J...

In [337]:
df12345.head(2)

,title,vote_average,release_date,runtime,imdb_id,poster_path,tags,genre,members
0,! [ai-ou],5.3,1991-01-26,108.0,NaN,/nb8ValoEsJdooZDOXfOt9uH8jIr.jpg,ai ou Three outsiders meet by chance and try t...,Action Drama Crime Comedy,Shigeru Saiki Kazukiyo Nishikiori Ryuusaku Shi...
1,!Aitsa,6.0,2023-03-16,89.0,tt27009737,/wrVlKVaLKdYbFgEsPtSCaGjMkS9.jpg,The ancient knowledge of indigenous peoples ch...,Documentary,Dane Dodds

In [338]:
df1to6=smart_merge(df12345,df6,key='title',priority='df12345')

In [339]:
df1to6.head(2)

,title,vote_average,release_date,runtime,imdb_id,poster_path,tags,genre,members
0,! [ai-ou],5.3,1991-01-26,108.0,NaN,/nb8ValoEsJdooZDOXfOt9uH8jIr.jpg,ai ou Three outsiders meet by chance and try t...,Action Drama Crime Comedy,Shigeru Saiki Kazukiyo Nishikiori Ryuusaku Shi...
1,!Aitsa,6.0,2023-03-16,89.0,tt27009737,/wrVlKVaLKdYbFgEsPtSCaGjMkS9.jpg,The ancient knowledge of indigenous peoples ch...,Documentary,Dane Dodds

## Dataset 7

In [420]:
df7=pd.read_csv(r"C:\Users\panka\Downloads\AI_Engineer\Projects\Data\New\IMDbMoviesIndia.csv",encoding="latin1")

In [421]:
df7.shape

(15509, 10)

In [422]:
df7.isnull().sum()

Name           0
Year         528
Duration    8269
Genre       1877
Rating      7590
Votes       7589
Director     525
Actor 1     1617
Actor 2     2384
Actor 3     3144
dtype: int64

In [423]:
df7['Votes'] = pd.to_numeric(
    df7['Votes'].astype(str).str.replace(',', '', regex=False),
    errors='coerce'  # anything unparseable becomes NaN instead of crashing
).fillna(0).astype(np.int64)

In [424]:
df7=df7[df7['Votes']>100]

In [425]:
df7.shape

(3220, 10)

In [426]:
df7.head()

,Name,Year,Duration,Genre,Rating,Votes,Director,Actor 1,Actor 2,Actor 3
5,...Aur Pyaar Ho Gaya,(1997),147 min,"Comedy, Drama, Musical",4.7,827,Rahul Rawail,Bobby Deol,Aishwarya Rai Bachchan,Shammi Kapoor
6,...Yahaan,(2005),142 min,"Drama, Romance, War",7.4,1086,Shoojit Sircar,Jimmy Sheirgill,Minissha Lamba,Yashpal Sharma
8,?: A Question Mark,(2012),82 min,"Horror, Mystery, Thriller",5.6,326,Allyson Patel,Yash Dave,Muntazir Ahmad,Kiran Bhatia
12,100 Days,(1991),161 min,"Horror, Romance, Thriller",6.5,983,Partho Ghosh,Jackie Shroff,Madhuri Dixit,Javed Jaffrey
13,100% Love,(2012),166 min,"Comedy, Drama, Romance",5.7,512,Rabi Kinagi,Jeet,Koyel Mallick,Sujoy Ghosh

In [427]:
df7.isnull().sum()

Name          0
Year          0
Duration    128
Genre         2
Rating        0
Votes         0
Director      0
Actor 1      12
Actor 2      22
Actor 3      30
dtype: int64

In [428]:
df7=combine_features(df7,['Genre'],new_col_name='genre')

In [429]:
df7.drop(columns=['Genre','Votes'],inplace=True)

In [430]:
df7.head(2)

,Name,Year,Duration,Rating,Director,Actor 1,Actor 2,Actor 3,genre
5,...Aur Pyaar Ho Gaya,(1997),147 min,4.7,Rahul Rawail,Bobby Deol,Aishwarya Rai Bachchan,Shammi Kapoor,Comedy Drama Musical
6,...Yahaan,(2005),142 min,7.4,Shoojit Sircar,Jimmy Sheirgill,Minissha Lamba,Yashpal Sharma,Drama Romance War

In [431]:
df7=combine_features(df7,['Director','Actor 1','Actor 2','Actor 3'],new_col_name='members')

In [432]:
df7.drop(columns=['Director','Actor 1','Actor 2','Actor 3'],inplace=True)

In [433]:
df7.head(3)

,Name,Year,Duration,Rating,genre,members
5,...Aur Pyaar Ho Gaya,(1997),147 min,4.7,Comedy Drama Musical,Rahul Rawail Bobby Deol Aishwarya Rai Bachchan...
6,...Yahaan,(2005),142 min,7.4,Drama Romance War,Shoojit Sircar Jimmy Sheirgill Minissha Lamba ...
8,?: A Question Mark,(2012),82 min,5.6,Horror Mystery Thriller,Allyson Patel Yash Dave Muntazir Ahmad Kiran B...

In [435]:
df7['Duration'] = pd.to_numeric(
    df7['Duration'].astype(str).str.replace(' min', '', regex=False),
    errors='coerce'  # anything unparseable becomes NaN instead of crashing
).fillna(0).astype(np.int64)

In [436]:
df7.head((3))

,Name,Year,Duration,Rating,genre,members
5,...Aur Pyaar Ho Gaya,(1997),147,4.7,Comedy Drama Musical,Rahul Rawail Bobby Deol Aishwarya Rai Bachchan...
6,...Yahaan,(2005),142,7.4,Drama Romance War,Shoojit Sircar Jimmy Sheirgill Minissha Lamba ...
8,?: A Question Mark,(2012),82,5.6,Horror Mystery Thriller,Allyson Patel Yash Dave Muntazir Ahmad Kiran B...

In [437]:
df1to6.head(3)

,title,vote_average,release_date,runtime,imdb_id,poster_path,tags,genre,members
0,! [ai-ou],5.3,1991-01-26,108.0,NaN,/nb8ValoEsJdooZDOXfOt9uH8jIr.jpg,ai ou Three outsiders meet by chance and try t...,Action Drama Crime Comedy,Shigeru Saiki Kazukiyo Nishikiori Ryuusaku Shi...
1,!Aitsa,6.0,2023-03-16,89.0,tt27009737,/wrVlKVaLKdYbFgEsPtSCaGjMkS9.jpg,The ancient knowledge of indigenous peoples ch...,Documentary,Dane Dodds
2,!W.A.R.: !Women Art Revolution,4.3,2010-09-12,83.0,tt1699720,/bUfLZKgGUXQMZLI7d9tUlT1Vdt9.jpg,feminism art woman director years in the makin...,Documentary,Carolee Schneemann Judy Chicago Claire Daigle ...

In [439]:
df7.rename(columns={'Name':'title','Duration':'runtime','Year':'release_date','Rating':'vote_average'},inplace=True)

In [440]:
df1to7=smart_merge(df1to6,df7,key='title',priority='df1to6')

In [442]:
df1to6.shape

(367395, 9)

In [444]:
df1to6.isnull().sum()

title               0
vote_average    14219
release_date     8234
runtime         14950
imdb_id         67042
poster_path     40435
tags                0
genre           11006
members         35429
dtype: int64

In [441]:
df1to7.shape

(367683, 9)

In [445]:
df1to7.isnull().sum()

title               0
vote_average    13937
release_date     8223
runtime         14730
imdb_id         67330
poster_path     40723
tags              288
genre           10902
members         35424
dtype: int64

In [447]:
df1to7.to_csv(r"C:\Users\panka\Downloads\AI_Engineer\Projects\Data\New\Dataset_d1to7.csv")

## Dataset 8

In [477]:
df8=pd.read_csv(r'C:\Users\panka\Downloads\AI_Engineer\Projects\Data\New\hollywood_highest_grossing.csv')

In [478]:
df8.head(3)

,Unnamed: 0,Title,Movie Info,Year,Release Date,Genre,Running Time
0,0,Avatar,A paraplegic Marine dispatched to the moon Pan...,2009,16-Dec-09,"['Action', 'Adventure', 'Fantasy', 'Sci-Fi']",2 hr 42 min
1,1,Avengers: Endgame,After the devastating events of Avengers: Infi...,2019,24-Apr-19,"['Action', 'Adventure', 'Drama', 'Sci-Fi']",3 hr 1 min
2,2,Avatar: The Way of Water,Jake Sully lives with his newfound family form...,2022,24-Apr-19,"['Action', 'Adventure', 'Drama', 'Sci-Fi']",3 hr 1 min

In [479]:
df8.shape

(1000, 7)

In [480]:
df8.drop(columns=['Unnamed: 0'],inplace=True)

In [481]:
df8.rename(columns={'Title':'title'},inplace=True)

In [482]:
df8=combine_features(df8,['Movie Info'],new_col_name='tags')

In [483]:
df8.head(3)

,title,Movie Info,Year,Release Date,Genre,Running Time,tags
0,Avatar,A paraplegic Marine dispatched to the moon Pan...,2009,16-Dec-09,"['Action', 'Adventure', 'Fantasy', 'Sci-Fi']",2 hr 42 min,A paraplegic Marine dispatched to the moon Pan...
1,Avengers: Endgame,After the devastating events of Avengers: Infi...,2019,24-Apr-19,"['Action', 'Adventure', 'Drama', 'Sci-Fi']",3 hr 1 min,After the devastating events of Avengers Infin...
2,Avatar: The Way of Water,Jake Sully lives with his newfound family form...,2022,24-Apr-19,"['Action', 'Adventure', 'Drama', 'Sci-Fi']",3 hr 1 min,Jake Sully lives with his newfound family form...

In [484]:
df8.drop(columns=['Movie Info'],inplace=True)

In [485]:
df8.head(3)

,title,Year,Release Date,Genre,Running Time,tags
0,Avatar,2009,16-Dec-09,"['Action', 'Adventure', 'Fantasy', 'Sci-Fi']",2 hr 42 min,A paraplegic Marine dispatched to the moon Pan...
1,Avengers: Endgame,2019,24-Apr-19,"['Action', 'Adventure', 'Drama', 'Sci-Fi']",3 hr 1 min,After the devastating events of Avengers Infin...
2,Avatar: The Way of Water,2022,24-Apr-19,"['Action', 'Adventure', 'Drama', 'Sci-Fi']",3 hr 1 min,Jake Sully lives with his newfound family form...

In [486]:
df8=combine_features(df8,['Genre'],new_col_name='genre')

In [487]:
df8.drop(columns=['Genre'],inplace=True)

In [488]:
df8.head(3)

,title,Year,Release Date,Running Time,tags,genre
0,Avatar,2009,16-Dec-09,2 hr 42 min,A paraplegic Marine dispatched to the moon Pan...,Action Adventure Fantasy Sci Fi
1,Avengers: Endgame,2019,24-Apr-19,3 hr 1 min,After the devastating events of Avengers Infin...,Action Adventure Drama Sci Fi
2,Avatar: The Way of Water,2022,24-Apr-19,3 hr 1 min,Jake Sully lives with his newfound family form...,Action Adventure Drama Sci Fi

In [489]:
import re
import numpy as np
import pandas as pd

def convert_runtime_to_minutes(df, col='Running Time', new_col='runtime_minutes'):
    def parse_runtime(value):
        if pd.isna(value):
            return np.nan
        value = str(value)
        hours = re.search(r'(\d+)\s*hr', value)
        minutes = re.search(r'(\d+)\s*min', value)
        total = 0
        if hours:
            total += int(hours.group(1)) * 60
        if minutes:
            total += int(minutes.group(1))
        return total if (hours or minutes) else np.nan

    df[new_col] = df[col].apply(parse_runtime)
    return df

df8 = convert_runtime_to_minutes(df8, col='Running Time', new_col='runtime_minutes')

In [492]:
df8.drop(columns=['Running Time'],inplace=True)

In [493]:
df8.head()

,title,Year,Release Date,tags,genre,runtime_minutes
0,Avatar,2009,16-Dec-09,A paraplegic Marine dispatched to the moon Pan...,Action Adventure Fantasy Sci Fi,162
1,Avengers: Endgame,2019,24-Apr-19,After the devastating events of Avengers Infin...,Action Adventure Drama Sci Fi,181
2,Avatar: The Way of Water,2022,24-Apr-19,Jake Sully lives with his newfound family form...,Action Adventure Drama Sci Fi,181
3,Titanic,1997,19-Dec-97,A seventeen year old aristocrat falls in love ...,Drama Romance,194
4,Star Wars: Episode VII - The Force Awakens,2015,16-Dec-15,As a new threat to the galaxy rises Rey a dese...,Action Adventure Sci Fi,138

In [494]:
df8.dtypes

title              object
Year                int64
Release Date       object
tags               object
genre              object
runtime_minutes     int64
dtype: object

In [495]:
df8.rename(columns={'Year':'release_date','runtime_minutes':'runtime'},inplace=True)

In [ ]:
df8.drop(columns=['Release Date'],inplace=True)

In [500]:
df8.head(2)

,title,release_date,tags,genre,runtime
0,Avatar,2009,A paraplegic Marine dispatched to the moon Pan...,Action Adventure Fantasy Sci Fi,162
1,Avengers: Endgame,2019,After the devastating events of Avengers Infin...,Action Adventure Drama Sci Fi,181

In [503]:
df8.shape

(1000, 5)

In [504]:
df1to8=smart_merge(df1to7,df8,key='title',priority='df1to7')

In [505]:
df1to8.head(3)

,title,vote_average,release_date,runtime,imdb_id,poster_path,tags,genre,members
0,! [ai-ou],5.3,1991-01-26,108.0,NaN,/nb8ValoEsJdooZDOXfOt9uH8jIr.jpg,ai ou Three outsiders meet by chance and try t...,Action Drama Crime Comedy,Shigeru Saiki Kazukiyo Nishikiori Ryuusaku Shi...
1,!Aitsa,6.0,2023-03-16,89.0,tt27009737,/wrVlKVaLKdYbFgEsPtSCaGjMkS9.jpg,The ancient knowledge of indigenous peoples ch...,Documentary,Dane Dodds
2,!W.A.R.: !Women Art Revolution,4.3,2010-09-12,83.0,tt1699720,/bUfLZKgGUXQMZLI7d9tUlT1Vdt9.jpg,feminism art woman director years in the makin...,Documentary,Carolee Schneemann Judy Chicago Claire Daigle ...

In [506]:
df1to8.isnull().sum()

title               0
vote_average    13957
release_date     8223
runtime         14730
imdb_id         67350
poster_path     40743
tags              288
genre           10902
members         35444
dtype: int64