## Dataset 1

In [14]:
import pandas as pd
df1=pd.read_csv(r"C:\Users\panka\Downloads\AI_Engineer\Projects\Data\New\TMDB_all_movies2.csv")

In [15]:
df1.head(2)

,id,title,vote_average,release_date,runtime,imdb_id,overview,tagline,genres,cast,director,poster_path,keywords
0,2,Ariel,7.118,1988-10-21,73.0,tt0094675,A Finnish man goes to the city to find a job a...,NaN,"Comedy, Drama, Romance, Crime","Turo Pajala, Susanna Haavisto, Matti Pellonpää...",Aki Kaurismäki,/ojDg0PGvs6R9xYFodRct2kdI6wC.jpg,"prison|underdog|helsinki, finland|factory work..."
1,3,Shadows in Paradise,7.300,1986-10-17,74.0,tt0092149,"Nikander, a rubbish collector and would-be ent...",NaN,"Comedy, Drama, Romance","Matti Pellonpää, Kati Outinen, Sakari Kuosmane...",Aki Kaurismäki,/nj01hspawPof0mJmlgfjuLyJuRN.jpg,"helsinki, finland|salesclerk|garbage"

In [16]:
df1.isnull().sum()

id                    0
title                15
vote_average          0
release_date     131347
runtime               0
imdb_id          551370
overview         189333
tagline         1043318
genres           331326
cast             389920
director         197724
poster_path      299577
keywords         883867
dtype: int64

In [18]:
df1=df1[df1["runtime"]>60]

In [20]:
df1.shape

(435921, 13)

In [21]:
df1.head(3)

,id,title,vote_average,release_date,runtime,imdb_id,overview,tagline,genres,cast,director,poster_path,keywords
0,2,Ariel,7.118,1988-10-21,73.0,tt0094675,A Finnish man goes to the city to find a job a...,NaN,"Comedy, Drama, Romance, Crime","Turo Pajala, Susanna Haavisto, Matti Pellonpää...",Aki Kaurismäki,/ojDg0PGvs6R9xYFodRct2kdI6wC.jpg,"prison|underdog|helsinki, finland|factory work..."
1,3,Shadows in Paradise,7.300,1986-10-17,74.0,tt0092149,"Nikander, a rubbish collector and would-be ent...",NaN,"Comedy, Drama, Romance","Matti Pellonpää, Kati Outinen, Sakari Kuosmane...",Aki Kaurismäki,/nj01hspawPof0mJmlgfjuLyJuRN.jpg,"helsinki, finland|salesclerk|garbage"
2,5,Four Rooms,5.905,1995-12-09,98.0,tt0113101,It's Ted the Bellhop's first night on the job....,Twelve outrageous guests. Four scandalous requ...,Comedy,"Sammi Davis, Salma Hayek Pinault, Lawrence Ben...","Quentin Tarantino, Robert Rodriguez, Alexandre...",/75aHn1NOYXh4M7L5shoeQ6NGykP.jpg,hotel|new year's eve|witch|bet|sperm|hotel roo...

In [22]:
df1.isnull().sum()

id                   0
title                4
vote_average         0
release_date     14670
runtime              0
imdb_id          92595
overview         15346
tagline         331661
genres           57730
cast             56055
director         44001
poster_path      46220
keywords        268452
dtype: int64

In [23]:
df1 = df1[~(df1["cast"].isna() & df1["director"].isna())]

In [25]:
df1.head(3)

,id,title,vote_average,release_date,runtime,imdb_id,overview,tagline,genres,cast,director,poster_path,keywords
0,2,Ariel,7.118,1988-10-21,73.0,tt0094675,A Finnish man goes to the city to find a job a...,NaN,"Comedy, Drama, Romance, Crime","Turo Pajala, Susanna Haavisto, Matti Pellonpää...",Aki Kaurismäki,/ojDg0PGvs6R9xYFodRct2kdI6wC.jpg,"prison|underdog|helsinki, finland|factory work..."
1,3,Shadows in Paradise,7.300,1986-10-17,74.0,tt0092149,"Nikander, a rubbish collector and would-be ent...",NaN,"Comedy, Drama, Romance","Matti Pellonpää, Kati Outinen, Sakari Kuosmane...",Aki Kaurismäki,/nj01hspawPof0mJmlgfjuLyJuRN.jpg,"helsinki, finland|salesclerk|garbage"
2,5,Four Rooms,5.905,1995-12-09,98.0,tt0113101,It's Ted the Bellhop's first night on the job....,Twelve outrageous guests. Four scandalous requ...,Comedy,"Sammi Davis, Salma Hayek Pinault, Lawrence Ben...","Quentin Tarantino, Robert Rodriguez, Alexandre...",/75aHn1NOYXh4M7L5shoeQ6NGykP.jpg,hotel|new year's eve|witch|bet|sperm|hotel roo...

In [27]:
df1.shape

(417854, 13)

In [26]:
df1.isnull().sum()

id                   0
title                4
vote_average         0
release_date      8679
runtime              0
imdb_id          80050
overview         14704
tagline         316811
genres           46179
cast             37988
director         25934
poster_path      38724
keywords        252036
dtype: int64

In [28]:
df1["keywords"] = df1["keywords"].fillna("")

In [29]:
df1 = df1.dropna(subset=["title", "overview", "genres"])

In [ ]:
df1["cast"] = df1["cast"].fillna("")
df1["director"] = df1["director"].fillna("")

In [31]:
df1.isnull().sum()

id                   0
title                0
vote_average         0
release_date      4511
runtime              0
imdb_id          53578
overview             0
tagline         264404
genres               0
cast                 0
director             0
poster_path      25903
keywords             0
dtype: int64

In [32]:
df1.shape

(361115, 13)

In [34]:
df1.head(2)

,id,title,vote_average,release_date,runtime,imdb_id,overview,tagline,genres,cast,director,poster_path,keywords
0,2,Ariel,7.118,1988-10-21,73.0,tt0094675,A Finnish man goes to the city to find a job a...,NaN,"Comedy, Drama, Romance, Crime","Turo Pajala, Susanna Haavisto, Matti Pellonpää...",Aki Kaurismäki,/ojDg0PGvs6R9xYFodRct2kdI6wC.jpg,"prison|underdog|helsinki, finland|factory work..."
1,3,Shadows in Paradise,7.300,1986-10-17,74.0,tt0092149,"Nikander, a rubbish collector and would-be ent...",NaN,"Comedy, Drama, Romance","Matti Pellonpää, Kati Outinen, Sakari Kuosmane...",Aki Kaurismäki,/nj01hspawPof0mJmlgfjuLyJuRN.jpg,"helsinki, finland|salesclerk|garbage"

In [37]:
df1.drop(columns=["id"],inplace=True)

In [39]:
df1.head(2)

,title,vote_average,release_date,runtime,imdb_id,overview,tagline,genres,cast,director,poster_path,keywords
0,Ariel,7.118,1988-10-21,73.0,tt0094675,A Finnish man goes to the city to find a job a...,NaN,"Comedy, Drama, Romance, Crime","Turo Pajala, Susanna Haavisto, Matti Pellonpää...",Aki Kaurismäki,/ojDg0PGvs6R9xYFodRct2kdI6wC.jpg,"prison|underdog|helsinki, finland|factory work..."
1,Shadows in Paradise,7.300,1986-10-17,74.0,tt0092149,"Nikander, a rubbish collector and would-be ent...",NaN,"Comedy, Drama, Romance","Matti Pellonpää, Kati Outinen, Sakari Kuosmane...",Aki Kaurismäki,/nj01hspawPof0mJmlgfjuLyJuRN.jpg,"helsinki, finland|salesclerk|garbage"

In [44]:
df1.to_csv(r"C:\Users\panka\Downloads\AI_Engineer\Projects\Data\New\TMDB_all_movies2.csv")

## Dataset 2

In [48]:
df2=pd.read_csv(r"C:\Users\panka\Downloads\AI_Engineer\Projects\Data\New\TMDB_all_movies1.csv")

In [49]:
df2.shape

(1474875, 13)

In [50]:
df2.head(2)

,id,title,vote_average,release_date,runtime,backdrop_path,homepage,imdb_id,overview,poster_path,tagline,genres,keywords
0,27205,Inception,8.364,2010-07-15,148,/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg,https://www.warnerbros.com/movies/inception,tt1375666,"Cobb, a skilled thief who commits corporate es...",/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg,Your mind is the scene of the crime.,"Action, Science Fiction, Adventure","rescue, mission, dream, airplane, paris, franc..."
1,157336,Interstellar,8.417,2014-11-05,169,/pbrkL804c8yAv3zBZR4QPEafpAR.jpg,http://www.interstellarmovie.net/,tt0816692,The adventures of a group of explorers who mak...,/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg,Mankind was born on Earth. It was never meant ...,"Adventure, Drama, Science Fiction","rescue, future, spacecraft, race against time,..."

In [52]:
df2=df2[df2["runtime"]>60]

In [54]:
df2.shape

(503437, 13)

In [55]:
df2 = df2.dropna(subset=["title", "overview", "genres"])

In [56]:
df2.shape

(316111, 13)

In [57]:
df2.isnull().sum()

id                    0
title                 0
vote_average          0
release_date       8663
runtime               0
backdrop_path    153957
homepage         265204
imdb_id           59969
overview              0
poster_path       35106
tagline          228972
genres                0
keywords         175268
dtype: int64

In [59]:
df1["keywords"] = df1["keywords"].fillna("")
df1["tagline"] = df1["tagline"].fillna("")

In [66]:
df2.head(2)

,id,title,vote_average,release_date,runtime,backdrop_path,homepage,imdb_id,overview,poster_path,tagline,genres,keywords,tags
0,27205,Inception,8.364,2010-07-15,148,/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg,https://www.warnerbros.com/movies/inception,tt1375666,"Cobb, a skilled thief who commits corporate es...",/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg,Your mind is the scene of the crime.,"Action, Science Fiction, Adventure","rescue, mission, dream, airplane, paris, franc...",rescue mission dream airplane paris france vir...
1,157336,Interstellar,8.417,2014-11-05,169,/pbrkL804c8yAv3zBZR4QPEafpAR.jpg,http://www.interstellarmovie.net/,tt0816692,The adventures of a group of explorers who mak...,/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg,Mankind was born on Earth. It was never meant ...,"Adventure, Drama, Science Fiction","rescue, future, spacecraft, race against time,...",rescue future spacecraft race against time art...

In [67]:
import pandas as pd
import re

def combine_features(df, feature_list, new_col_name='combined_features', sep=' '):
    """
    Combines multiple string-based columns of a dataframe into a single new column.
    Any character that is NOT an alphabet letter (a-z, A-Z) is treated as a separator
    (this includes commas, spaces, periods, quotes, digits, hyphens, colons, etc.).

    Parameters:
        df (pd.DataFrame): The input dataframe.
        feature_list (list of str): List of column names to combine.
        new_col_name (str): Name of the new combined feature column.
        sep (str): Separator to join the final combined words with (default: single space).

    Returns:
        pd.DataFrame: The dataframe with the new combined feature column added.
    """
    df = df.copy()

    # Validate that all requested features exist in the dataframe
    missing = [f for f in feature_list if f not in df.columns]
    if missing:
        raise ValueError(f"These columns are not in the dataframe: {missing}")

    def process_row(row):
        words = []
        for feature in feature_list:
            value = row[feature]

            # Handle NaN / None gracefully
            if pd.isna(value):
                continue

            value = str(value)

            # Split on ANY non-alphabet character (letters only survive as tokens)
            tokens = re.split(r'[^a-zA-Z]+', value.strip())
            tokens = [t.strip() for t in tokens if t.strip() != '']

            words.extend(tokens)

        return sep.join(words)

    df[new_col_name] = df.apply(process_row, axis=1)
    return df

In [68]:
df2 = combine_features(df2, ['keywords', 'tagline', 'overview'], new_col_name='tags')
df2[['tags']].head(2)

                                                tags
0  rescue mission dream airplane paris france vir...
1  rescue future spacecraft race against time art...

In [69]:
df2["tags"][0]

'rescue mission dream airplane paris france virtual reality kidnapping philosophy spy allegory manipulation car crash heist memory architecture los angeles california dream world subconscious Your mind is the scene of the crime Cobb a skilled thief who commits corporate espionage by infiltrating the subconscious of his targets is offered a chance to regain his old life as payment for a task considered to be impossible inception the implantation of another person s idea into a target s subconscious'

In [71]:
df2.head(2)

,id,title,vote_average,release_date,runtime,backdrop_path,homepage,imdb_id,overview,poster_path,tagline,genres,keywords,tags
0,27205,Inception,8.364,2010-07-15,148,/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg,https://www.warnerbros.com/movies/inception,tt1375666,"Cobb, a skilled thief who commits corporate es...",/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg,Your mind is the scene of the crime.,"Action, Science Fiction, Adventure","rescue, mission, dream, airplane, paris, franc...",rescue mission dream airplane paris france vir...
1,157336,Interstellar,8.417,2014-11-05,169,/pbrkL804c8yAv3zBZR4QPEafpAR.jpg,http://www.interstellarmovie.net/,tt0816692,The adventures of a group of explorers who mak...,/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg,Mankind was born on Earth. It was never meant ...,"Adventure, Drama, Science Fiction","rescue, future, spacecraft, race against time,...",rescue future spacecraft race against time art...

In [73]:
df2.drop(columns=["tagline","keywords","overview"],inplace=True)

In [74]:
df2.head(2)

,id,title,vote_average,release_date,runtime,backdrop_path,homepage,imdb_id,poster_path,genres,tags
0,27205,Inception,8.364,2010-07-15,148,/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg,https://www.warnerbros.com/movies/inception,tt1375666,/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg,"Action, Science Fiction, Adventure",rescue mission dream airplane paris france vir...
1,157336,Interstellar,8.417,2014-11-05,169,/pbrkL804c8yAv3zBZR4QPEafpAR.jpg,http://www.interstellarmovie.net/,tt0816692,/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg,"Adventure, Drama, Science Fiction",rescue future spacecraft race against time art...

In [75]:
df2 = combine_features(df2, ['genres'], new_col_name='genre')
df2[['genre']].head(2)

                              genre
0  Action Science Fiction Adventure
1   Adventure Drama Science Fiction

In [76]:
df2.drop(columns=['genres'],inplace=True)

In [77]:
df2.head(2)

,id,title,vote_average,release_date,runtime,backdrop_path,homepage,imdb_id,poster_path,tags,genre
0,27205,Inception,8.364,2010-07-15,148,/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg,https://www.warnerbros.com/movies/inception,tt1375666,/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg,rescue mission dream airplane paris france vir...,Action Science Fiction Adventure
1,157336,Interstellar,8.417,2014-11-05,169,/pbrkL804c8yAv3zBZR4QPEafpAR.jpg,http://www.interstellarmovie.net/,tt0816692,/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg,rescue future spacecraft race against time art...,Adventure Drama Science Fiction

In [78]:
df1.head(2)

,title,vote_average,release_date,runtime,imdb_id,overview,tagline,genres,cast,director,poster_path,keywords
0,Ariel,7.118,1988-10-21,73.0,tt0094675,A Finnish man goes to the city to find a job a...,,"Comedy, Drama, Romance, Crime","Turo Pajala, Susanna Haavisto, Matti Pellonpää...",Aki Kaurismäki,/ojDg0PGvs6R9xYFodRct2kdI6wC.jpg,"prison|underdog|helsinki, finland|factory work..."
1,Shadows in Paradise,7.300,1986-10-17,74.0,tt0092149,"Nikander, a rubbish collector and would-be ent...",,"Comedy, Drama, Romance","Matti Pellonpää, Kati Outinen, Sakari Kuosmane...",Aki Kaurismäki,/nj01hspawPof0mJmlgfjuLyJuRN.jpg,"helsinki, finland|salesclerk|garbage"

In [ ]:
df1 = combine_features(df1, ['keywords', 'tagline', 'overview'], new_col_name='tags')

In [83]:
df1['tags'][0]

'prison underdog helsinki finland factory worker prisoner falling in love A Finnish man goes to the city to find a job after the mine where he worked is closed and his father commits suicide'

In [84]:
df1 = combine_features(df1, ['genres'], new_col_name='genre')
df1['genre'][0]

'Comedy Drama Romance Crime'

In [85]:
df1.head(2)

,title,vote_average,release_date,runtime,imdb_id,overview,tagline,genres,cast,director,poster_path,keywords,tags,genre
0,Ariel,7.118,1988-10-21,73.0,tt0094675,A Finnish man goes to the city to find a job a...,,"Comedy, Drama, Romance, Crime","Turo Pajala, Susanna Haavisto, Matti Pellonpää...",Aki Kaurismäki,/ojDg0PGvs6R9xYFodRct2kdI6wC.jpg,"prison|underdog|helsinki, finland|factory work...",prison underdog helsinki finland factory worke...,Comedy Drama Romance Crime
1,Shadows in Paradise,7.300,1986-10-17,74.0,tt0092149,"Nikander, a rubbish collector and would-be ent...",,"Comedy, Drama, Romance","Matti Pellonpää, Kati Outinen, Sakari Kuosmane...",Aki Kaurismäki,/nj01hspawPof0mJmlgfjuLyJuRN.jpg,"helsinki, finland|salesclerk|garbage",helsinki finland salesclerk garbage Nikander a...,Comedy Drama Romance

In [86]:
df1.drop(columns=['overview','tagline','keywords'],inplace=True)

In [87]:
df1 = combine_features(df1, ['cast','director'], new_col_name='members')

In [88]:
df1['members'][0]

'Turo Pajala Susanna Haavisto Matti Pellonp Eetu Hilkamo Erkki Pajala Matti Jaaranen Hannu Viholainen Jorma Markkula Tarja Kein nen Eino Kuusela Kauko Laalo Jyrki Olsonen Esko Nikkari Marja Packal n Mikko Remes Tomi Salmela Reijo Marin Heikki Salomaa Veikko Uusim ki Esko Salminen Hannu Kivisalo Pekka Wilen Heikki Anttila Pentti Auer Timo Harakka Kari Helasepp Juuso Hirvikangas Hanna Jokinen Sakari Kuosmanen Sami Lanki Jouko Lumme Mikko Lyytik inen Timo Markko Merja Pulkkinen Markku Rantala Sirkka Rautiainen Jaakko Talaskivi Timo Toikka Olli Varja Aki Kaurism ki'

In [89]:
df1.isnull().sum()

title               0
vote_average        0
release_date     4511
runtime             0
imdb_id         53578
genres              0
cast                0
director            0
poster_path     25903
tags                0
genre               0
members             0
dtype: int64

In [90]:
df1.drop(columns=['genres','cast','director'],inplace=True)

In [92]:
df1.head(2)

,title,vote_average,release_date,runtime,imdb_id,poster_path,tags,genre,members
0,Ariel,7.118,1988-10-21,73.0,tt0094675,/ojDg0PGvs6R9xYFodRct2kdI6wC.jpg,prison underdog helsinki finland factory worke...,Comedy Drama Romance Crime,Turo Pajala Susanna Haavisto Matti Pellonp Eet...
1,Shadows in Paradise,7.300,1986-10-17,74.0,tt0092149,/nj01hspawPof0mJmlgfjuLyJuRN.jpg,helsinki finland salesclerk garbage Nikander a...,Comedy Drama Romance,Matti Pellonp Kati Outinen Sakari Kuosmanen Es...

In [93]:
df2.head(2)

,id,title,vote_average,release_date,runtime,backdrop_path,homepage,imdb_id,poster_path,tags,genre
0,27205,Inception,8.364,2010-07-15,148,/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg,https://www.warnerbros.com/movies/inception,tt1375666,/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg,rescue mission dream airplane paris france vir...,Action Science Fiction Adventure
1,157336,Interstellar,8.417,2014-11-05,169,/pbrkL804c8yAv3zBZR4QPEafpAR.jpg,http://www.interstellarmovie.net/,tt0816692,/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg,rescue future spacecraft race against time art...,Adventure Drama Science Fiction

In [95]:
import pandas as pd

def merge_datasets(df1, df2, subset_col='title'):
    
    df_combined = pd.concat([df1, df2], axis=0, ignore_index=True, sort=False)

    
    df_combined = df_combined.drop_duplicates(subset=subset_col, keep='first').reset_index(drop=True)

    return df_combined

In [97]:
df12 = merge_datasets(df1, df2)
df12.head(2)

,title,vote_average,release_date,runtime,imdb_id,poster_path,tags,genre,members,id,backdrop_path,homepage
0,Ariel,7.118,1988-10-21,73.0,tt0094675,/ojDg0PGvs6R9xYFodRct2kdI6wC.jpg,prison underdog helsinki finland factory worke...,Comedy Drama Romance Crime,Turo Pajala Susanna Haavisto Matti Pellonp Eet...,NaN,NaN,NaN
1,Shadows in Paradise,7.300,1986-10-17,74.0,tt0092149,/nj01hspawPof0mJmlgfjuLyJuRN.jpg,helsinki finland salesclerk garbage Nikander a...,Comedy Drama Romance,Matti Pellonp Kati Outinen Sakari Kuosmanen Es...,NaN,NaN,NaN

In [ ]:
print(df1.shape, df2.shape, df12.shape)
print(df12.columns.tolist())
print(df12.isna().sum())

(361115, 9) (316111, 11) (351385, 12)
['title', 'vote_average', 'release_date', 'runtime', 'imdb_id', 'poster_path', 'tags', 'genre', 'members', 'id', 'backdrop_path', 'homepage']
title                 0
vote_average          0
release_date       6005
runtime               0
imdb_id           64409
poster_path       27919
tags                  0
genre                 0
members           34089
id               317296
backdrop_path    336255
homepage         346773
dtype: int64

In [102]:
df12.drop(columns=['id','backdrop_path','homepage'],inplace=True)

In [103]:
df12.head(2)

,title,vote_average,release_date,runtime,imdb_id,poster_path,tags,genre,members
0,Ariel,7.118,1988-10-21,73.0,tt0094675,/ojDg0PGvs6R9xYFodRct2kdI6wC.jpg,prison underdog helsinki finland factory worke...,Comedy Drama Romance Crime,Turo Pajala Susanna Haavisto Matti Pellonp Eet...
1,Shadows in Paradise,7.300,1986-10-17,74.0,tt0092149,/nj01hspawPof0mJmlgfjuLyJuRN.jpg,helsinki finland salesclerk garbage Nikander a...,Comedy Drama Romance,Matti Pellonp Kati Outinen Sakari Kuosmanen Es...

In [106]:
df12.to_csv(r'C:\Users\panka\Downloads\AI_Engineer\Projects\Data\New\Dataset_d12.csv')

## Dataset 3

In [108]:
df3=pd.read_csv(r"C:\Users\panka\Downloads\AI_Engineer\Projects\Data\New\TrendingMovies.csv")

In [109]:
df3.head(2)

,id,title,overview,vote_average,release_date
0,969681,Spider-Man: Brand New Day,Fighting crime full-time as Spider-Man in a wo...,7.864,2026-07-29
1,1368337,The Odyssey,"Odysseus, the legendary King of Ithaca, embark...",8.000,2026-07-15

In [110]:
df3.shape

(9996, 5)

In [ ]:
df3 = combine_features(df3, ['overview'], new_col_name='tags')

In [119]:
df3.drop(columns=['id'],inplace=True)

In [120]:
df12.columns

Index(['title', 'vote_average', 'release_date', 'runtime', 'imdb_id',
       'poster_path', 'tags', 'genre', 'members'],
      dtype='object')

In [121]:
df123 =merge_datasets(df12,df3,subset_col='title')

In [122]:
df123.head(2)

,title,vote_average,release_date,runtime,imdb_id,poster_path,tags,genre,members
0,Ariel,7.118,1988-10-21,73.0,tt0094675,/ojDg0PGvs6R9xYFodRct2kdI6wC.jpg,prison underdog helsinki finland factory worke...,Comedy Drama Romance Crime,Turo Pajala Susanna Haavisto Matti Pellonp Eet...
1,Shadows in Paradise,7.300,1986-10-17,74.0,tt0092149,/nj01hspawPof0mJmlgfjuLyJuRN.jpg,helsinki finland salesclerk garbage Nikander a...,Comedy Drama Romance,Matti Pellonp Kati Outinen Sakari Kuosmanen Es...

In [123]:
print(df12.shape,df123.shape)

(351385, 9) (352957, 9)

In [125]:
df123.to_csv(r'C:\Users\panka\Downloads\AI_Engineer\Projects\Data\New\Dataset_d123.csv')

## Dataset 4